<?php
/**
 * DummyPrintTransport.php
 *
 * @author  Will Perring <will@supernatural.ninja>
 * @since   24/06/2020
 */

namespace Core\Printing\PrinterTransport;


use Core\Interfaces\PrintableMedia;
use Core\Printing\PrinterTransport;
use Core\Printing\PrintingResult;

class DummyPrintTransport extends PrinterTransport {
	
	protected $_delay;
	
	public function __construct( $delay=0 ) {
		$this->_delay = $delay;
	}
	
	protected function _transport( PrintableMedia $media ) {

		sleep( $this->_delay );
		
		return new PrintingResult( true, [
			'detail' => 'This was generated by the Dummy Print Transport. No printing occurred'
		]);
	}
	
}
